### ISSUE TITLE
Looks awesome :) - would PoE be a thing to do?

### ISSUE THREAD

**Issue by felixn-unity** [ThomasVon2021/pikvm-board#17]

**Comment by hzzfly** [comment]
Yes



At 2022-02-11 14:41:22, "felixn-unity" ***@***.***> wrote:

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by m50S79sM6SRNp8Jn** [comment]
The new BliKVM PCIe version supports PoE.

**Comment by ThomasVon2021** [comment]
Hat and PCIe version all support PoE.
