### ISSUE TITLE
KVM Switches

### ISSUE THREAD

**Issue by jwansek** [ThomasVon2021/pikvm-board#33]
Has anyone tested any KVM switches to extend the functionality across multiple computers? If so it might be nice if this was added to the documentation.

Alternatively, since this project uses the pikvm project as an upstream, is it safe to assume that the KVM switches listed in that projects documentation also work with this?

**Comment by ThomasVon2021** [comment]
Yes， the KVM switches listed in pikvm projects documentation also work.

**Comment by m50S79sM6SRNp8Jn** [comment]
[BliKVM discord @https://discord.gg/dwx7vKYt](https://discord.gg/dwx7vKYt)

**Comment by jwansek** [comment]
Thanks. I'll join the discord. Hopefully I'll be able to test a few new KVM switches after my KVM arrives.

**Comment by m50S79sM6SRNp8Jn** [comment]
It's my understanding that some KVM switches don't play nice with BliKVM. I think this is because those KVM switches don't much adhere to standards. Sorry I don't have more details but wanted to share the information with you.

**Comment by arjanwaard** [comment]
For controlling just 2 systems I use  29 euro AIMOS HDMI KVM switch, https://amzn.eu/d/6knC4yF
Works fine with hotkey switching ootb.
