### ISSUE TITLE
Include copyright notice for third-party code

### ISSUE THREAD

**Issue by mtlynch** [ThomasVon2021/pikvm-board#38]
[`./src/blikvm.sh`](https://github.com/ThomasVon2021/pikvm-board/blob/0142e55508ab025a58b64e8250b72867e49f4d15/src/blikvm.sh) seems to be derived from TinyPilot's copyrighted code here:

https://github.com/tiny-pilot/tinypilot/blob/609b36faf2352cb0922111b2fc9f13bd73824855/quick-install

TinyPilot's code is released [under the MIT license](https://github.com/tiny-pilot/tinypilot/blob/master/LICENSE), so you're welcome to include it, but the license requires preserving the copyright notice and license.

You can get back into compliance with the license this by copying the text from [TinyPilot's license](https://github.com/tiny-pilot/tinypilot/blob/master/LICENSE) as a header at the top of the file or by including TinyPilot's license in a file called `NOTICE` at the root of the repo.

**Comment by ThomasVon2021** [comment]
Thank you for reminding me. I have modified it

**Comment by mtlynch** [comment]
@ThomasVon2021 can you link to the commit? As of the latest commit, blikvm.sh is still missing the copyright header

https://github.com/ThomasVon2021/pikvm-board/blob/master/src/blikvm.sh

**Comment by melroyvandenberg** [comment]
I also don't see the MIT header. Nor a NOTICE file. 😢 

@ThomasVon2021 You know what, maybe you just also should add a LICENSE file? If you license under MIT, then it's all compatible and no confusion anymore.
